// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tgpviedbxgnliochccod.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRncHZpZWRieGdubGlvY2hjY29kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4NjY1OTIsImV4cCI6MjA2NDQ0MjU5Mn0.ud3NnH3mJW4cWnutEyMaDUNWoSCBbfw-na5nKkoVTXA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);